# permissions for end users to view mlflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlflow-viewer-role
rules:
- apiGroups:
  - webapp.plural.sh
  resources:
  - mlflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.plural.sh
  resources:
  - mlflows/status
  verbs:
  - get
