# permissions for end users to edit mlflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlflow-editor-role
rules:
- apiGroups:
  - webapp.plural.sh
  resources:
  - mlflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.plural.sh
  resources:
  - mlflows/status
  verbs:
  - get
